[parser]
url_link_key = ">"
url_link_key_escape = "\\>"
lore_link_key = "="
lore_link_key_escape = "\\="
comment_key = "%"
comment_key_escape = "\\%"
breakline_key = "---"
breakline_key_escape = "\\---"
image_key = "|"
image_key_escape = "\\|"
placeholder_key = "_"
placeholder_key_escape = "\\_"

[renderer]
site_title = "?"
from_lore_path = "./docs"
to_html_path = "./target"
lang = "zh-CN"
link_base = "https://localLore.github.io/laer-image-concept-block16-special-solid-select-color"
scripts = [
    "https://fleetinglore.github.io/lore-pages-src/default/main.js",
]
